# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fast"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = false
	# Enable block entities light source.
	block_entities = false
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				trapped_chest = true
				blast_furnace = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.ants]
				nest = true

			[light_sources.settings.block_entities.environmentz]
				laval_cauldron_block_entity = true

			[light_sources.settings.block_entities.biomemakeover]
				tapestry = true
				altar = true
				lightning_bug_bottle = true
				poltergeist = true
				directional_data = true

			[light_sources.settings.block_entities.snowyspirit]
				glow_lights = true

			[light_sources.settings.block_entities.another_furniture]
				service_bell = true
				planter_box = true
				curtain = true
				shelf = true

			[light_sources.settings.block_entities.galosphere]
				aura_ringer = true

			[light_sources.settings.block_entities.lunade]
				copper_fitting = true
				copper_pipe = true

			[light_sources.settings.block_entities.bountiful]
				board-be = true

			[light_sources.settings.block_entities.brazier]
				brazier = true

			[light_sources.settings.block_entities.immersive_weathering]
				icicle = true

			[light_sources.settings.block_entities.ecologics]
				pot = true
				sign = true

			[light_sources.settings.block_entities.dehydration]
				campfire_cauldron_entity = true

			[light_sources.settings.block_entities.waystones]
				sharestone = true
				portstone = true
				warp_plate = true
				waystone = true

			[light_sources.settings.block_entities.dramaticdoors]
				tall_netherite_door = true

			[light_sources.settings.block_entities.purpeille]
				ancient_gateway_block_entity = true
				monolithic_purpur_block_entity = true
				end_rubble = true
				ancient_guardian_block_entity = true
				ancient_oven_block_entity = true

			[light_sources.settings.block_entities.seasons]
				greenhouse_glass = true
				season_detector = true

			[light_sources.settings.block_entities.overweight_farming]
				overweight_apple = true

			[light_sources.settings.block_entities.everycomp]
				fd_cabinet = true
				af_planter_box = true
				af_shelf = true

			[light_sources.settings.block_entities.the_bumblezone]
				honey_cocoon = true
				incense_candle = true

			[light_sources.settings.block_entities.cauldron_dyeing]
				water_cauldron_entity = true

			[light_sources.settings.block_entities.charm]
				kiln = true
				totem_block = true
				variant_chest = true
				bookcase = true
				trapped_chest = true

			[light_sources.settings.block_entities.fishery]
				fish_trap = true
				fishermans_barrel = true

			[light_sources.settings.block_entities.supplementaries]
				pedestal = true
				clock_block = true
				wall_lantern = true
				blackboard = true
				flag = true
				sack = true
				speaker_block = true
				key_lockable_tile = true
				bubble_block = true
				bellows = true
				notice_board = true
				skull_pile = true
				ceiling_banner = true
				jar_boat = true
				cage = true
				skull_candle = true
				bamboo_spikes = true
				hanging_sign_oak = true
				trapped_present = true
				hourglass = true
				wind_vane = true
				doormat = true
				jar = true
				spring_launcher_arm = true
				item_shelf = true
				turn_table = true
				faucet = true
				structure_temp = true
				block_generator = true
				book_pile = true
				rope_knot = true
				hanging_flower_pot = true
				statue = true
				goblet = true
				urn = true
				flower_box = true
				pulley_block = true
				globe = true
				timber_frame = true
				safe = true
				present = true
				sign_post = true

			[light_sources.settings.block_entities.numismatic-overhaul]
				shop = true

			[light_sources.settings.block_entities.alloy_forgery]
				forge_controller = true

			[light_sources.settings.block_entities.copperhopper]
				copper_hopper_entity = true

			[light_sources.settings.block_entities.lootr]
				special_loot_chest = true
				special_trapped_loot_chest = true
				special_loot_shulker = true
				special_loot_barrel = true
				special_loot_inventory = true

			[light_sources.settings.block_entities.comforts]
				hammock = true
				sleeping_bag = true

			[light_sources.settings.block_entities.snowrealmagic]
				snow = true
				texture_tile = true

			[light_sources.settings.block_entities.ad_astra]
				flag_entity = true
				globe_entity = true
				fuel_refinery_entity = true
				compressor_entity = true
				coal_generator_entity = true
				oxygen_loader_entity = true
				solar_panel_entity = true
				nasa_workbench_entity = true
				oxygen_distributor_entity = true
				water_pump_entity = true
				energizer_entity = true
				cryo_freezer_entity = true
				oxygen_sensor = true
				sliding_door = true
				launch_pad = true
				cable = true
				fluid_pipe = true

			[light_sources.settings.block_entities.spirit]
				soul_cage = true
				soul_pedestal = true
				pedestal = true

			[light_sources.settings.block_entities.vitalize]
				pylon = true
				soul_translator = true

			[light_sources.settings.block_entities.pyrotastic]
				fireworks_crate = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				cobweb = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				falling_icicle = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				falling_ash = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				falling_sand_layer = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				falling_propagule = true
				skeleton = true
				falling_leaf_layer = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				vex = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.ants]
				red_ant = true
				brown_ant = true
				black_ant = true
				gold_ant = true
				muddy_ant = true

			[light_sources.settings.entities.ratsmischief]
				rat = true

			[light_sources.settings.entities.sculk_worm]
				sculk_worm_entity = true
				sculk_segment_entity = true

			[light_sources.settings.entities.biomemakeover]
				rootling = true
				tadpole = true
				cowboy = true
				lightning_bug = true
				scuttler = true
				moth = true
				owl = true
				glowfish = true
				toad = true
				lightning_bug_alternate = true
				adjudicator_mimic = true
				helmit_crab = true
				bm_chest_boat = true
				decayed = true
				dragonfly = true
				stone_golem = true
				adjudicator = true
				blightbat = true
				ghost = true
				mushroom_trader = true
				lightning_bottle = true
				tumbleweed = true
				bm_boat = true

			[light_sources.settings.entities.snowyspirit]
				container_entity = true
				sled = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.la_cucaracha]
				splash_bottled_roach = true
				roach = true

			[light_sources.settings.entities.galosphere]
				sparkle = true
				silver_bomb = true

			[light_sources.settings.entities.impaled]
				elder_trident = true
				hellfork = true
				soulfork = true
				pitchfork = true
				atlan = true
				guardian_trident = true

			[light_sources.settings.entities.naturalist]
				rattlesnake = true
				deer = true
				zebra = true
				snail = true
				canary = true
				firefly = true
				rhino = true
				hippo = true
				bluejay = true
				snake = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				robin = true
				caterpillar = true
				boar = true
				butterfly = true
				giraffe = true
				bear = true
				elephant = true

			[light_sources.settings.entities.corners]
				dimensional_painting = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.brazier]
				crazed = true
				crazed_flame = true

			[light_sources.settings.entities.strawgolem]
				strawnggolem = true
				strawgolem = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				camel = true
				chest_boat = true
				boat = true
				penguin = true
				coconut_crab = true

			[light_sources.settings.entities.mcdw]
				summoned_bee = true

			[light_sources.settings.entities.tdnf]
				falling_log = true

			[light_sources.settings.entities.vanilla_degus]
				degu = true

			[light_sources.settings.entities.unvotedandshelved]
				glare = true
				copper_golem = true
				oxidized_copper_golem = true

			[light_sources.settings.entities.overweight_farming]
				overweight_apple_falling_block = true

			[light_sources.settings.entities.lucys_sloths]
				sloth = true

			[light_sources.settings.entities.twigs]
				pebble = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				shriek_worm = true
				sculk_leech = true
				chest_boat = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.the_bumblezone]
				honey_slime = true
				pollen_puff = true
				thrown_stinger_spear = true
				bee_queen = true
				honey_crystal_shard = true
				beehemoth = true
				bee_stinger = true

			[light_sources.settings.entities.hedgehog]
				hedgehog = true

			[light_sources.settings.entities.charm]
				moobloom = true
				chair = true
				endermite_powder = true
				coral_squid = true

			[light_sources.settings.entities.aqupd]
				caracal = true

			[light_sources.settings.entities.frozenup]
				chilloo = true

			[light_sources.settings.entities.hauntedharvest]
				splattered_egg = true

			[light_sources.settings.entities.dummmmmmy]
				dummy_number = true
				target_dummy = true

			[light_sources.settings.entities.creeperspores]
				creeperling = true

			[light_sources.settings.entities.untitledduckmod]
				duck_egg = true
				duck = true
				goose = true
				goose_egg = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				falling_ash = true
				falling_lantern = true
				falling_urn = true
				brick_projectile = true
				pearl_marker = true
				falling_sack = true
				red_merchant = true
				bomb = true
				rope_arrow = true

			[light_sources.settings.entities.frame]
				seat = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.ad_astra]
				lunarian_wandering_trader = true
				glacian_ram = true
				tier_3_rocket = true
				space_painting = true
				tier_1_rover = true
				pygro = true
				zombified_pygro = true
				sulfur_creeper = true
				zombified_mogler = true
				tier_4_rocket = true
				lander = true
				lunarian = true
				corrupted_lunarian = true
				star_crawler = true
				martian_raptor = true
				pygro_brute = true
				mogler = true
				tier_1_rocket = true
				tier_2_rocket = true
				ice_spit_entity = true

			[light_sources.settings.entities.spirit]
				soul_arrow = true
				soul = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.pyrotastic]
				fireworks_crate = true

