enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 7.5
leavesCullingMode = "DEFAULT"
leavesCullingDepth = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
mcwfences = true
pigsteel = true
everycomp = true
purpeille = true
farmersdelight = true
bountiful = true
sihywtcamd = true
alloy_forgery = true
overweight_farming = true
excavated_variants = true
mcwwindows = true
brewery = true
mighty_mangoes = true
mahogany = true
galosphere = true
another_furniture = true
frozenup = true
ecologics = true
twigs = true
copperhopper = true
endless_cake = true
dramaticdoors = true
comforts = true
mythicupgrades = true
blossom = true
chalk = true
effectivecrystals = true
snowyspirit = true
archeology = true
mcwtrpdoors = true
lunade = true
mahjongcraft = true
croptosis = true
dehydration = true
aspen = true
snowrealmagic = true
lightstones = true
charm = true
treechop = true
vitalize = true
betterlily = true
customportalapi = true
naturalist = true
mcwdoors = true
automated_crafting = true
supplementaries = true
portablehole = true
deeperdarker = true
biomemakeover = true
spirit = true
seasons = true
ants = true
woof = true
corners = true
architects_palette = true
minecraft = true
unvotedandshelved = true
lootr = true
sculk_worm = true
colorful-azaleas = true
expandedstorage = true
wardentools = true
creeperoverhaul = true
waystones = true
immersive_weathering = true
hedgehog = true
numismatic-overhaul = true
pyrotastic = true
universal_graves = true
moyai = true
brazier = true
puddles = true
ad_astra = true
netherdepthsupgrade = true
skylorlib = true
